language: rust
rust:
  - stable
cache: cargo

os: linux

addons:
  apt:
    packages:
      - libsdl2-dev

before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo clippy -- -D warnings
  - cargo build --verbose --release
  - cargo test --verbose
