[package]
authors = ["vigdail <vigdail.dev@gmail.com>"]
edition = "2018"
name = "raytracer"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.2"
rand = "0.7.3"
threadpool = "1.8.1"
